// Copyright 2024 The Kaia Authors
// This file is part of the Kaia library.
//
// The Kaia library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The Kaia library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the Kaia library. If not, see <http://www.gnu.org/licenses/>.
package core

import (
	"fmt"
	"testing"
	"time"

	"github.com/kaiachain/kaia/consensus/bft"
	"github.com/stretchr/testify/require"
)

// These suites run independent real cores one event at a time. Honest messages
// come from core.broadcast; only explicitly Byzantine nodes may inject votes.
// No core.Start goroutines or wall-clock sleeps are used. The scheduler drives
// the same handleEvent and timer callbacks used by the production event loop.
//
// Scope: fixed council/committee, rotating proposer, authenticated full-mesh
// delivery, and empty blocks. This does not model production gossip caches,
// transaction execution, fetcher insertion, or dynamic validator selection.
func TestConsensusNormal(t *testing.T) {
	t.Run("SingleBlock", func(t *testing.T) {
		for _, permissionless := range []bool{false, true} {
			t.Run(fmt.Sprintf("Permissionless=%t", permissionless), func(t *testing.T) {
				net := newTestNetwork(t, 4, &testNetworkOpts{permissionless: permissionless})
				proposal := net.proposal(0, 1)
				net.submit(0, proposal)
				require.Empty(t, net.nodes[0].backend.committed, "submission only queues an event")
				net.drain()
				net.assertCommitted(proposal, 0)
			})
		}
	})
	t.Run("ConsecutiveBlocks", func(t *testing.T) {
		net := newTestNetwork(t, 4, nil)
		for height := uint64(1); height <= 4; height++ {
			proposer := int(height-1) % 4
			proposal := net.proposal(proposer, 1)
			net.submit(proposer, proposal)
			net.drain()
			net.assertCommitted(proposal, 0)
			for _, node := range net.nodes {
				require.Equal(t, height+1, node.core.current.Sequence().Uint64())
				require.Equal(t, StateAcceptRequest, node.core.state)
				require.False(t, node.core.current.IsHashLocked())
				require.Zero(t, node.core.current.Prepares.Size())
				require.Zero(t, node.core.current.Commits.Size())
			}
		}
	})
}

func TestConsensusNonByzantineFault(t *testing.T) {
	t.Run("PrepareBeforeProposal", func(t *testing.T) {
		net := newTestNetwork(t, 4, nil)
		proposal := net.proposal(0, 1)
		net.submit(0, proposal)
		require.NoError(t, net.deliverRequest(0))
		require.NoError(t, net.deliver(0, 0, bft.MsgPreprepare))
		require.ErrorIs(t, net.deliver(0, 1, bft.MsgPrepare), errFutureMessage)
		require.Zero(t, net.nodes[1].core.current.Prepares.Size())
		require.False(t, net.backlog(1, 0).Empty())
		require.NoError(t, net.deliver(0, 1, bft.MsgPreprepare))
		net.drain()
		net.assertCommitted(proposal, 0)
		require.True(t, net.backlog(1, 0).Empty())
	})
	t.Run("SilentProposer", func(t *testing.T) {
		net := newTestNetwork(t, 4, nil)
		net.crash(0)
		timeout := net.roundTimeout()
		net.advance(timeout - time.Nanosecond)
		require.Empty(t, net.queue)
		for _, node := range net.nodes[1:] {
			require.Zero(t, node.core.current.Round().Uint64())
		}
		net.advance(time.Nanosecond)
		// Timer callbacks enqueue timeout events; no core has processed them yet.
		require.Len(t, net.queue, 3)
		net.drain()
		for _, node := range net.nodes[1:] {
			require.Equal(t, uint64(1), node.core.current.Round().Uint64())
			require.False(t, node.core.waitingForRoundChange)
			timer := node.core.roundChangeTimer.Load().(*testTimer)
			require.True(t, timer.active)
			require.Equal(t, net.now+timeout+2*time.Second, timer.due)
		}
		proposal := net.proposal(1, 1)
		net.submit(1, proposal)
		net.drain()
		net.assertCommitted(proposal, 1)
		require.Empty(t, net.nodes[0].backend.committed)
	})
}

func TestConsensusByzantineFault(t *testing.T) {
	// A qualified validator outside the committee must not influence proposal
	// admission or vote counts. Valid inputs are generated by the other cores.
	t.Run("NonCommitteeSender", func(t *testing.T) {
		net := newTestNetwork(t, 5, &testNetworkOpts{committeeSize: 4})
		net.makeByzantine(4)
		target := net.nodes[1].core
		proposal := net.proposal(0, 1)

		// PREPREPARE: rejected because node 4 is not the round-0 proposer.
		net.inject(4, 1, bft.MsgPreprepare, net.proposal(4, 1), 0)
		require.ErrorIs(t, net.deliver(4, 1, bft.MsgPreprepare), errNotFromProposer)
		require.Nil(t, target.current.Preprepare)

		net.submit(0, proposal)
		require.NoError(t, net.deliverRequest(0))
		for _, to := range []int{1, 0, 2} {
			require.NoError(t, net.deliver(0, to, bft.MsgPreprepare))
		}
		require.Equal(t, proposal.Hash(), target.current.Proposal().Hash())

		// PREPARE: correct subject, but the sender holds no committee seat.
		net.inject(4, 1, bft.MsgPrepare, proposal, 0)
		require.ErrorIs(t, net.deliver(4, 1, bft.MsgPrepare), errNotFromCommittee)
		require.Zero(t, target.current.Prepares.Size())
		require.NoError(t, net.deliver(0, 1, bft.MsgPrepare))
		require.Equal(t, 1, target.current.Prepares.Size())

		// Deliver a prepare quorum to node 0 so its core produces a real COMMIT.
		for _, from := range []int{0, 1, 2} {
			require.NoError(t, net.deliver(from, 0, bft.MsgPrepare))
		}
		// COMMIT: same, and it must not count toward the commit quorum.
		net.inject(4, 1, bft.MsgCommit, proposal, 0)
		require.ErrorIs(t, net.deliver(4, 1, bft.MsgCommit), errNotFromCommittee)
		require.Zero(t, target.current.Commits.Size())
		require.NoError(t, net.deliver(0, 1, bft.MsgCommit))
		require.Equal(t, 1, target.current.Commits.Size())

		// ROUND CHANGE: rejected too, so the round-1 set stays empty until a
		// committee member times out and sends its own.
		net.inject(4, 1, bft.MsgRoundChange, proposal, 1)
		require.ErrorIs(t, net.deliver(4, 1, bft.MsgRoundChange), errNotFromCommittee)
		require.Nil(t, target.roundChangeSet.roundChanges[1])
		net.advance(net.roundTimeout())
		require.NoError(t, net.stepTimeout(2))
		require.ErrorIs(t, net.deliver(2, 1, bft.MsgRoundChange), errIgnored)
		require.Equal(t, 1, target.roundChangeSet.roundChanges[1].Size())
	})

	// Byzantine voters sign another digest, while
	// honest nodes produce their own PREPAREs and COMMITs through the network.
	t.Run("ConflictingVotes", func(t *testing.T) {
		for _, badCount := range []int{1, 3} {
			t.Run(fmt.Sprintf("Byzantine=%d", badCount), func(t *testing.T) {
				net := newTestNetwork(t, 4, nil)
				honestCount := 4 - badCount
				for i := honestCount; i < 4; i++ {
					net.makeByzantine(i)
				}
				proposal := net.proposal(0, 1)
				other := net.proposal(0, 2)
				net.submit(0, proposal)
				require.NoError(t, net.deliverRequest(0))
				for i := 0; i < honestCount; i++ {
					require.NoError(t, net.deliver(0, i, bft.MsgPreprepare))
					for j := honestCount; j < 4; j++ {
						for _, code := range []uint64{bft.MsgPrepare, bft.MsgCommit} {
							net.inject(j, i, code, other, 0)
							require.ErrorIs(t, net.deliver(j, i, code), errInconsistentSubject)
						}
					}
					require.Zero(t, net.nodes[i].core.current.GetPrepareOrCommitSize())
				}
				net.drain()
				if badCount == 1 {
					net.assertCommitted(proposal, 0)
				} else {
					require.Empty(t, net.nodes[0].backend.committed)
					require.Equal(t, StatePreprepared, net.nodes[0].core.state)
					require.Equal(t, 1, net.nodes[0].core.current.Prepares.Size())
				}
			})
		}
	})

	// Only the proposer equivocates; each honest
	// core independently votes for the proposal delivered to its group.
	t.Run("EquivocatingProposer", func(t *testing.T) {
		for _, count := range []int{5, 7} {
			t.Run(fmt.Sprintf("Validators=%d", count), func(t *testing.T) {
				net := newTestNetwork(t, count, nil)
				net.makeByzantine(0)
				a, b := net.proposal(0, 1), net.proposal(0, 2)
				require.NotEqual(t, a.Hash(), b.Hash())
				for i := 1; i < count; i++ {
					proposal := a
					if i > (count-1)/2 {
						proposal = b
					}
					net.inject(0, i, bft.MsgPreprepare, proposal, 0)
					require.NoError(t, net.deliver(0, i, bft.MsgPreprepare))
					net.inject(0, i, bft.MsgPrepare, proposal, 0)
				}
				// Cross-group votes are delivered too; honest cores must reject
				// them instead of the harness concealing conflicting messages.
				net.drain(errInconsistentSubject)
				for _, node := range net.nodes[1:] {
					require.Empty(t, node.backend.committed)
					require.Equal(t, StatePreprepared, node.core.state)
					require.Equal(t, (count-1)/2+1, node.core.current.Prepares.Size())
					require.False(t, node.core.current.IsHashLocked())
				}
			})
		}
	})
}
